# Generated by Django 4.1.2 on 2022-10-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('price', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=10000)),
                ('release_date', models.CharField(max_length=1000)),
                ('lte_exists', models.CharField(max_length=1000)),
                ('slug', models.SlugField(max_length=1000)),
            ],
        ),
    ]
